---
    - hosts: all                                        
      become: yes
      tasks:
        - name: Add apt repository
          become: true
          apt_repository:
            repo: ppa:openjdk-r/ppa
            state: present

        - name: Update apt
          become: true
          apt:
            update_cache: yes
        
        - name: Install apt package
          become: true
          apt:
            name: "{{ item }}"
            state: present
          with_items:
            - git
            - software-properties-common
            - python3.8
            - python3-pip
            - openjdk-8-jdk
            - openjdk-8-jre

        # - name: Install JAVA
        #   command: "{{ item }}"         
        #   with_items:
        #     - sudo apt -y update
        #     - sudo apt -y install openjdk-8-jre
        #   become: true
        #   apt:
            # name: "{{ packages }}"
            # state: present
        #   vars:
            # packages:
            #   - default-jre
            #   - default-jdk
            #   - openjdk-8-jre
            #   - openjdk-8-jdk
            
        - name: Download Tomcat
          get_url:
            url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
            dest: /tmp/apache-tomcat-9.0.54.tar.gz
            mode: '0755'
            group: ubuntu
            owner: ubuntu

        - name: Extracting Tomcat             
          unarchive:
            src: /tmp/apache-tomcat-9.0.54.tar.gz
            dest: /opt/
            remote_src: yes

        - name: Configuring Tomcat
          become: true
          command: "{{ item }}"         
          with_items:
            - chown -RH ubuntu:ubuntu /opt/apache-tomcat-9.0.54/
            - chmod +x /opt/apache-tomcat-9.0.54/bin/catalina.sh
            - chmod +x /opt/apache-tomcat-9.0.54/bin/startup.sh 

        # - name : Run Tomcat
        #   shell: nohup /opt/apache-tomcat-9.0.54/bin/startup.sh &
